// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// fs_cpp
NumericMatrix fs_cpp(NumericMatrix z, int levels);
RcppExport SEXP _gghalftone_fs_cpp(SEXP zSEXP, SEXP levelsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type z(zSEXP);
    Rcpp::traits::input_parameter< int >::type levels(levelsSEXP);
    rcpp_result_gen = Rcpp::wrap(fs_cpp(z, levels));
    return rcpp_result_gen;
END_RCPP
}
// pip_cpp
LogicalVector pip_cpp(NumericVector px, NumericVector py, NumericVector vx, NumericVector vy);
RcppExport SEXP _gghalftone_pip_cpp(SEXP pxSEXP, SEXP pySEXP, SEXP vxSEXP, SEXP vySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type px(pxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type py(pySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type vx(vxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type vy(vySEXP);
    rcpp_result_gen = Rcpp::wrap(pip_cpp(px, py, vx, vy));
    return rcpp_result_gen;
END_RCPP
}
// dt_cpp
NumericMatrix dt_cpp(LogicalMatrix m);
RcppExport SEXP _gghalftone_dt_cpp(SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< LogicalMatrix >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(dt_cpp(m));
    return rcpp_result_gen;
END_RCPP
}
// dt_col_cpp
NumericMatrix dt_col_cpp(LogicalMatrix m);
RcppExport SEXP _gghalftone_dt_col_cpp(SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< LogicalMatrix >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(dt_col_cpp(m));
    return rcpp_result_gen;
END_RCPP
}
// scan_fill_cpp
LogicalMatrix scan_fill_cpp(NumericVector rx, NumericVector ry, NumericVector vx, NumericVector vy);
RcppExport SEXP _gghalftone_scan_fill_cpp(SEXP rxSEXP, SEXP rySEXP, SEXP vxSEXP, SEXP vySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type rx(rxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ry(rySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type vx(vxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type vy(vySEXP);
    rcpp_result_gen = Rcpp::wrap(scan_fill_cpp(rx, ry, vx, vy));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_gghalftone_fs_cpp", (DL_FUNC) &_gghalftone_fs_cpp, 2},
    {"_gghalftone_pip_cpp", (DL_FUNC) &_gghalftone_pip_cpp, 4},
    {"_gghalftone_dt_cpp", (DL_FUNC) &_gghalftone_dt_cpp, 1},
    {"_gghalftone_dt_col_cpp", (DL_FUNC) &_gghalftone_dt_col_cpp, 1},
    {"_gghalftone_scan_fill_cpp", (DL_FUNC) &_gghalftone_scan_fill_cpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_gghalftone(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
