# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fs_cpp <- function(z, levels) {
    .Call(`_gghalftone_fs_cpp`, z, levels)
}

pip_cpp <- function(px, py, vx, vy) {
    .Call(`_gghalftone_pip_cpp`, px, py, vx, vy)
}

dt_cpp <- function(m) {
    .Call(`_gghalftone_dt_cpp`, m)
}

dt_col_cpp <- function(m) {
    .Call(`_gghalftone_dt_col_cpp`, m)
}

scan_fill_cpp <- function(rx, ry, vx, vy) {
    .Call(`_gghalftone_scan_fill_cpp`, rx, ry, vx, vy)
}

